# Generated by Django 4.2.16 on 2024-10-22 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recolector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=8, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('nombre', models.CharField()),
                ('apellido', models.CharField()),
                ('saldo', models.FloatField()),
            ],
        ),
    ]
