# Generated by Django 4.2.16 on 2024-10-22 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_recolector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recolector',
            name='apellido',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recolector',
            name='nombre',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recolector',
            name='saldo',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
