# Generated by Django 4.2.16 on 2024-10-02 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_material', models.CharField(choices=[('plastico', 'Plástico'), ('papel', 'Papel'), ('vidrio', 'Vidrio'), ('metal', 'Metal'), ('organico', 'Orgánico')], max_length=50)),
                ('cantidad', models.PositiveIntegerField()),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiales', to='my_app.formulario')),
            ],
        ),
    ]
